apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: roboshop
spec:
  # list of containers
  containers:
  - name: debug
    image: 123456246/debug:v1
    #here with this line port will not be opened, just for information
    command: ["sleep", "100000"]